# Generated by Django 4.1 on 2025-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('createdate', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='trainee/imgs')),
            ],
        ),
    ]
