# Generated by Django 4.1 on 2025-03-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_trainee_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='track',
        ),
    ]
