# Generated by Django 4.1 on 2025-03-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0006_alter_trainee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='test',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
