# Generated by Django 4.1 on 2025-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0008_remove_trainee_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
