# Generated by Django 4.1 on 2025-03-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0009_trainee_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='test',
        ),
    ]
