# Generated by Django 4.1 on 2025-03-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(db_column='Name', max_length=50),
        ),
    ]
