# Generated by Django 4.2 on 2025-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
